# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWLnG6UsAiG28bKtQmctOdNrIv17rGJu

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
ontology_prefix = Namespace("http://oeg.fi.upm.es/def/people#")
person_prefix = Namespace("http://oeg.fi.upm.es/resource/person/")

# If we wanted to include the prefixes in the graph:
g.namespace_manager.bind('ontology', ontology_prefix)
g.namespace_manager.bind('person', person_prefix)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO

# Classes
g.add((ontology_prefix.Person, RDF.type, RDFS.Class))
g.add((ontology_prefix.Professor, RDF.type, RDFS.Class))
g.add((ontology_prefix.fullProfessor, RDF.type, RDFS.Class))
g.add((ontology_prefix.associateProfessor, RDF.type, RDFS.Class))
g.add((ontology_prefix.interimAssociateProfessor, RDF.type, RDFS.Class))

# Labels
g.add((ontology_prefix.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((ontology_prefix.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((ontology_prefix.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))
g.add((ontology_prefix.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((ontology_prefix.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))

# Subclasses
g.add((ontology_prefix.Professor, RDFS.subClassOf, ontology_prefix.Person))
g.add((ontology_prefix.FullProfessor, RDFS.subClassOf, ontology_prefix.Professor))
g.add((ontology_prefix.AssociateProfessor, RDFS.subClassOf, ontology_prefix.Professor))
g.add((ontology_prefix.InterimAssociateProfessor, RDFS.subClassOf, ontology_prefix.AssociateProfessor))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO

g.add((ontology_prefix.hasColleague, RDF.type, RDF.Property))
g.add((ontology_prefix.hasColleague, RDFS.domain, ontology_prefix.Person))
g.add((ontology_prefix.hasColleague, RDFS.range, ontology_prefix.Person))
g.add((ontology_prefix.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))

g.add((ontology_prefix.hasHomePage, RDF.type, RDF.Property))
g.add((ontology_prefix.hasHomePage, RDFS.domain, ontology_prefix.FullProfessor))
g.add((ontology_prefix.hasHomePage, RDFS.range, RDFS.Literal))
g.add((ontology_prefix.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))

g.add((ontology_prefix.hasName, RDF.type, RDF.Property))
g.add((ontology_prefix.hasName, RDFS.domain, ontology_prefix.Person))
g.add((ontology_prefix.hasName, RDFS.range, RDFS.Literal))
g.add((ontology_prefix.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO

g.add((person_prefix.Asun, RDF.type, ontology_prefix.FullProfessor))
g.add((person_prefix.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((person_prefix.Asun, ontology_prefix.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))
g.add((person_prefix.Asun, ontology_prefix.hasColleague, person_prefix.Raul))

g.add((person_prefix.Oscar, RDF.type, ontology_prefix.AssociateProfessor))
g.add((person_prefix.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((person_prefix.Oscar, ontology_prefix.hasName, Literal("Oscar Corcho García", datatype=XSD.string)))
g.add((person_prefix.Oscar, ontology_prefix.hasColleague, person_prefix.Asun))

g.add((person_prefix.Raul, RDF.type, ontology_prefix.InterimAssociateProfessor))
g.add((person_prefix.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
g.namespace_manager.bind('vcard', VCARD)
g.namespace_manager.bind('foaf', FOAF)

g.add((person_prefix.Oscar, FOAF.email, Literal("oscar.corcho@upm.es", datatype=XSD.String)))
g.add((person_prefix.Oscar, VCARD.Given, Literal("Oscar", datatype=XSD.string)))
g.add((person_prefix.Oscar, VCARD.Family, Literal("Corcho García", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")