# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muTWPNCizLD_t6DBqR70UJv53uzps6uW

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
result = []

for s, p, o in g.triples((None, RDF.type, RDFS.Class)):
    superclass = g.value(s, RDFS.subClassOf)  # returns None if the superclass is missing
    result.append((s, superclass))

for r in result:
    print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  "Select ?c ?sc where {?c rdf:type rdfs:Class. OPTIONAL {?c rdfs:subClassOf ?sc}}"

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

#asun --> associate profesor (ns.person)


ns = Namespace("http://oeg.fi.upm.es/def/people#")
person = ns.Person

tree_classes = [person] #add the classes in the list
classes_left = [person] # used to extrct elements from the list

while classes_left:
    c = classes_left.pop()
    for sc in g.subjects(RDFS.subClassOf, c):
        tree_classes.append(sc)
        classes_left.append(sc)


individuals = []
for t in tree_classes:
    for s in g.subjects(RDF.type, t):
        individuals.append(s)

# visualizar resultados
for i in individuals:
    print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """ SELECT ?ind
WHERE {
  ?ind rdf:type ?c .
  ?c rdfs:subClassOf* ontology:Person .
}"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =  """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?type
WHERE {
  ?person ns:knows ns:Rocky .
  ?person rdf:type ?type .
  ?person rdfs:label ?name .
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =  """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT ?name
WHERE {
  {
    ?person ns:hasColleague ?friend .
    ?friend ns:ownsPet ?dog .
    ?dog rdf:type ns:Animal .
    ?person rdfs:label ?name .
  }
  UNION
  {
    ?person ns:hasColleague ?friend_1 .
    ?friend_1 ns:hasColleague ?friend_2 .
    ?frined_22 ns:ownsPet ?dog .
    ?pet2 rdf:type ns:Animal .
    ?person rdfs:label ?name .
  }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
