# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkmmU0Nw0b8YzJqwc6qnpnn5ZJkEeK2x

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person = Namespace("http://oeg.fi.upm.es/resource/person/")

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
result = []

for clase in g.subjects(RDF.type, RDFS.Class):
    # Buscar superclase, si existe
    superclase = None
    for sc in g.objects(clase, RDFS.subClassOf):
        superclase = sc
        break
    result.append((clase, superclase))

# Visualize the results

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

from rdflib import RDF, RDFS

# SPARQL completa
query = """
SELECT ?c ?sc
WHERE {
    ?c rdf:type rdfs:Class .
    OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
"""

# query =  "Select "

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

# variable to return
individuals = []

# Buscamos todas las clases, que sean subclases de Person:

subclasses = set()
pending = [ontology.Person]  # empezamos con Person


while pending:
    current = pending.pop()
    subclasses.add(current)
    # buscamos clases que sean subclases de la actual
    for s in g.subjects(RDFS.subClassOf, current):
        if s not in subclasses:
            pending.append(s)


print(subclasses)


# Sacamos los individuos o instancias de estas subclases
for cls in subclasses:
    for ind in g.subjects(RDF.type, cls):
        individuals.append(ind)


# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

# subClassOf*: las subclases y las subclases de esas subclases, osea va sacando subclases hasta el punto mas bajo

query = """
# PREFIX ontology: <http://oeg.fi.upm.es/def/people#>

SELECT ?ind
WHERE {
  ?ind rdf:type ?class .
  ?class rdfs:subClassOf* ontology:Person .
}
"""


for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

# TO DO

query = """
PREFIX ontology: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?type
WHERE {
  ?person ontology:knows ontology:Rocky .
  ?person rdfs:label ?name .
  ?person a ?type .
}
"""

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

# TO D0

query = """
PREFIX ontology: <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?name
WHERE {
  {
    # Caso 1: un conocido tiene perro
    ?person ontology:hasColleague ?colleague .
    ?colleague ontology:ownsPet ?pet .
    ?pet rdf:type ontology:Animal .
  }
  UNION
  {
    # Caso 2: un conocido de un conocido tiene un perro
    ?person ontology:hasColleague ?colleague1 .
    ?colleague1 ontology:hasColleague ?colleague2 .
    ?colleague2 ontology:ownsPet ?pet2 .
    ?pet2 rdf:type ontology:Animal .
  }

  ?person rdfs:label ?name .
}
"""


# Visualize the results
for r in g.query(query):
  print(r.name)

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")