# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huqqm2xQL2oAvYZt2G8M3Byp_KqoORUt

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
# --- Recolectar todas las clases ---
classes = set()

# 1) Clases declaradas explícitamente
for c in g.subjects(RDF.type, RDFS.Class):
    classes.add(c)

# 2) Clases que aparecen en axiomas de subClassOf (como subclase u superclase)
for s, o in g.subject_objects(RDFS.subClassOf):
    classes.add(s)  # subclase
    classes.add(o)  # superclase

# --- Construir (class, superclass) ---
result = []
for c in classes:
    superclasses = list(g.objects(c, RDFS.subClassOf))
    if superclasses:
        for sup in superclasses:
            result.append((c, sup))
    else:
        result.append((c, None))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """SELECT DISTINCT ?c ?sc
WHERE {
  {
    { ?c a rdfs:Class }
    UNION
    { ?c rdfs:subClassOf ?_any }
    UNION
    { ?_any rdfs:subClassOf ?c }
  }
  OPTIONAL { ?c rdfs:subClassOf ?sc }
}
ORDER BY ?c ?sc
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")
# --- 1) Recolectar Person + TODAS sus subclases (transitivas) ---
person_and_subs = set([ns.Person])
frontier = [ns.Person]

while frontier:
    current = frontier.pop()
    for sub in g.subjects(RDFS.subClassOf, current):
        if sub not in person_and_subs:
            person_and_subs.add(sub)
            frontier.append(sub)

# --- 2) Obtener individuos tipados en cualquiera de esas clases ---
ind_set = set()
for cls in person_and_subs:
    for s in g.subjects(RDF.type, cls):
        ind_set.add(s)

# --- 3) Lista final ordenada (por string) ---
individuals = sorted(ind_set, key=str)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?ind
WHERE {
  ?ind a ?cls .
  ?cls rdfs:subClassOf* <http://oeg.fi.upm.es/def/people#Person> .
}
ORDER BY ?ind
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?name ?type
WHERE {
  ?person ns:knows ns:Rocky.
  ?person rdfs:label ?name.
  ?person a ?type.
}
ORDER BY ?name ?type
"""

# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX people: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?name
WHERE {
    {
      ?person people:hasColleague / people:ownsPet ?perro.
      ?perro rdf:type people:Animal .
    }
    UNION
    {
      ?person people:hasColleague / people:hasColleague / people:ownsPet ?perro.
      ?perro rdf:type people:Animal .
    }
    ?person rdfs:label ?name .
  }
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
