# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FPSiShKbRoJHKGtce7bstUQplIXBUuE

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

PERSON = Namespace("http://oeg.fi.upm.es/resource/person/")
ONTOLOGY = Namespace("http://oeg.fi.upm.es/def/people#")

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

class_definitions = {
    "Person": ["Person", None],
    "Professor": ["Professor", "Person"],
    "FullProfessor": ["FullProfessor", "Professor"],
    "AssociateProfessor": ["AssociateProfessor", "Professor"],
    "InterimAssociateProfessor": ["InterimAssociateProfessor", "AssociateProfessor"],
}

for class_name, (label_text, superclass_name) in class_definitions.items():
    class_uri = ONTOLOGY[class_name]

    g.add((class_uri, RDF.type, RDFS.Class))
    g.add((class_uri, RDFS.label, Literal(label_text, datatype=XSD.string)))

    if superclass_name:
        superclass_uri = ONTOLOGY[superclass_name]
        g.add((class_uri, RDFS.subClassOf, superclass_uri))

for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

property_definitions = {
    "hasColleague": {"label": "hasColleague", "domain": ONTOLOGY.Person, "range": ONTOLOGY.Person},
    "hasName": {"label": "hasName", "domain": ONTOLOGY.Person, "range": RDFS.Literal},
    "hasHomePage": {"label": "hasHomePage", "domain": ONTOLOGY.FullProfessor, "range": RDFS.Literal},
}

for prop_name, props in property_definitions.items():
    prop_uri = ONTOLOGY[prop_name]

    g.add((prop_uri, RDF.type, RDF.Property))
    g.add((prop_uri, RDFS.label, Literal(props["label"], datatype=XSD.string)))
    g.add((prop_uri, RDFS.domain, props["domain"]))
    g.add((prop_uri, RDFS.range, props["range"]))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

individual_definitions = {
    "Oscar": {"class": ONTOLOGY.AssociateProfessor, "label": "Oscar"},
    "Asun": {"class": ONTOLOGY.FullProfessor, "label": "Asun"},
    "Raul": {"class": ONTOLOGY.InterimAssociateProfessor, "label": "Raul"},
}

for ind_name, ind_props in individual_definitions.items():
    ind_uri = PERSON[ind_name]
    g.add((ind_uri, RDF.type, ind_props["class"]))
    g.add((ind_uri, RDFS.label, Literal(ind_props["label"], datatype=XSD.string)))

data_triples = [
    (PERSON.Oscar, ONTOLOGY.hasName, Literal("Oscar")),
    (PERSON.Oscar, ONTOLOGY.hasColleague, PERSON.Asun),

    (PERSON.Asun, ONTOLOGY.hasColleague, PERSON.Raul),
    (PERSON.Asun, ONTOLOGY.hasHomePage, Literal("https://asun.homepage")), # SIN DATATYPE

    (PERSON.Raul, ONTOLOGY.hasColleague, PERSON.Asun),
]

for s, p, o in data_triples:
    g.add((s, p, o))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")

g.bind('vcard', VCARD)
g.bind('foaf', FOAF)

contact_details = [
    (PERSON.Oscar, VCARD.Family, Literal("García", datatype=XSD.string)),
    (PERSON.Oscar, VCARD.Given, Literal("García", datatype=XSD.string)),
    (PERSON.Oscar, FOAF.email, Literal("García", datatype=XSD.string))
]

for s, p, o in contact_details:
    g.add((s, p, o))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")