# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0x_AwbhSNuEWnKOaZCbmqYAPLm9EY7i

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
# Visualize the results
result = [] #list of tuples

for s,p,o in g.triples((None, RDF.type, RDFS.Class)): #extract all classes
  o2 = g.value(s, RDFS.subClassOf, None) #for each subject we are going to extract only one result
  result.append((s, o2)) #list of tuples

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """
SELECT ?c ?sc
WHERE {
    ?c a rdfs:Class .
    OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

# Find all subclasses of Person (including Person)
subclasses = set()
to_explore = [ns.Person] #list of classes to explore

while to_explore:
    cls = to_explore.pop() #remove last class added
    subclasses.add(cls)
    for sub in g.subjects(RDFS.subClassOf, cls): #triples (sub, rdfs:subClassOf, cls) here we look for classes that are subClassOf Person
        if sub not in subclasses:
            to_explore.append(sub)

# Find individuals of Person or its subclasses
for cls in subclasses:
    for ind in g.subjects(RDF.type, cls):
        if ind not in individuals:
            individuals.append(ind)

# Visualize results
for i in individuals:
    print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = """
PREFIX ontology: <http://oeg.fi.upm.es/def/people#>

SELECT ?ind
WHERE {
    ?ind a ?c .
    ?c rdfs:subClassOf* ontology:Person .
}
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

#in this exercise we cannot use hasName because it is not defined
query =  """
PREFIX : <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?type
WHERE {
    ?p :knows :Rocky .
    ?p rdf:type ?type .
    ?p rdfs:label ?name .
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
    print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =  """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?name
WHERE {
  {
    ?p :hasColleague ?colleague .
    ?colleague :ownsPet ?pet .
    ?p rdfs:label ?name .
  }
  UNION
  {
    ?p :hasColleague ?colleague1 .
    ?colleague1 :hasColleague ?colleague2 .
    ?colleague2 :ownsPet ?pet2 .
    ?p rdfs:label ?name .
  }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")

