# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvi3kyXEC4pjKj4Sfkn3XWdGJP0I6Wvc

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
ONTOLOGY=Namespace("http://oeg.fi.upm.es/def/people#")
PERSON=Namespace("http://oeg.fi.upm.es/resource/person/")

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

g.namespace_manager.bind('ontology', ONTOLOGY)
g.namespace_manager.bind('person', PERSON)

# Definiciones de uris de clases y etiquetas
class_uri_labels=[
    (ONTOLOGY.InterimAssociateProfessor, "InterimAssociateProfessor"),
    (ONTOLOGY.AssociateProfessor,"AssociateProfessor"),
    (ONTOLOGY.FullProfessor,"FullProfessor"),
    (ONTOLOGY.Professor,"Professor"),
    (ONTOLOGY.Person,"Person")
]

#Añadimos las clases con sus etiquetas y el tipo de datos
for uri,label in class_uri_labels:
  g.add((uri,RDF.type, RDFS.Class))
  g.add((uri,RDFS.label, Literal(label, datatype=XSD.string)))

#Incluimos la jerarquía
g.add((ONTOLOGY.InterimAssociateProfessor,RDFS.subClassOf,ONTOLOGY.AssociateProfessor))
g.add((ONTOLOGY.AssociateProfessor,RDFS.subClassOf,ONTOLOGY.Professor))
g.add((ONTOLOGY.FullProfessor,RDFS.subClassOf,ONTOLOGY.Professor))
g.add((ONTOLOGY.Professor,RDFS.subClassOf,ONTOLOGY.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

#Creamos una lista en la que se define el uri de la propiedad,la etiqueta, el dominio y el rango
property_list=[
    (ONTOLOGY.hasName,"hasName",ONTOLOGY.Person,RDFS.Literal),
    (ONTOLOGY.hasColleague,"hasColleague",ONTOLOGY.Person,ONTOLOGY.Person),
    (ONTOLOGY.hasHomePage,"hasHomePage",ONTOLOGY.FullProfessor,RDFS.Literal)
]
#Añadimos cada propiedad a partir de la lista superior
for uri,label,domain,range in property_list:
  g.add((uri,RDF.type,RDF.Property))
  g.add((uri,RDFS.label, Literal(label, datatype=XSD.string)))
  g.add((uri,RDFS.domain,domain))
  g.add((uri,RDFS.range,range))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

#Oscar y sus propiedades
g.add((PERSON.Oscar,RDF.type,ONTOLOGY.AssociateProfessor))
g.add((PERSON.Oscar,RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((PERSON.Oscar,ONTOLOGY.hasName,Literal("Óscar Corcho García",)))
g.add((PERSON.Oscar,ONTOLOGY.hasColleague,PERSON.Asun))

#Asun y sus propiedades
g.add((PERSON.Asun,RDF.type,ONTOLOGY.FullProfessor))
g.add((PERSON.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((PERSON.Asun,ONTOLOGY.hasHomePage,Literal("http://oeg.fi.upm.es/",datatype=XSD.string)))
g.add((PERSON.Asun,ONTOLOGY.hasColleague,PERSON.Raul))

#Raul y sus propiedades
g.add((PERSON.Raul,RDF.type,ONTOLOGY.InterimAssociateProfessor))
g.add((PERSON.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

FOAF = Namespace("http://xmlns.com/foaf/0.1/")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

g.add((PERSON.Oscar,VCARD.Given,Literal("Óscar", datatype=XSD.string)))
g.add((PERSON.Oscar,VCARD.Family,Literal("Corcho García", datatype=XSD.string)))
g.add((PERSON.Oscar,FOAF.email,Literal("oscarcg@example.es", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")