# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPzY9L86W842x15GziLNZfVDhXt8vfze

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

result = [] #list of tuples
for classes in set(g.subjects(RDF.type, RDFS.Class)):
   superclass= g.objects(classes,RDFS.subClassOf)
   if superclass:
        result.append((classes,superclass))
   else:
        result.append((classes,None))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

from rdflib.plugins.sparql import prepareQuery
query =  prepareQuery('''
SELECT ?c ?sc  WHERE {
    ?c rdf:type rdfs:Class.
	OPTIONAL{?c rdfs:subClassOf ?sc}.
  }
 ''',
 initNs = { "rdf": RDF, "rdfs": RDFS}
)

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ONTOLOGY = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

#Creamos el conjunto que localiza las clases que son subclases de Person, set() para evitar duplicados
subclasses = set()

#Conjunto de clases pendientes a revisar sus subclases, empezamos por la clase person
visit_class={ONTOLOGY.Person}

#Ejecutamos la búsqueda recursiva, mientras haya clases pendientes de revisar
while visit_class:
  current = visit_class.pop() #tomamos una de las clases a revisar, y la quitamos de la lista de pendientes
  subclasses.add(current) #notar que incluimos class pq es instancias de la clase o subclase de person
  for subclass in g.subjects(RDFS.subClassOf, current):
    if subclass not in subclasses:
      visit_class.add(subclass) #si no hemos visitado todavía sus subclases lo hacemos

#Cogemos todas las instancias que tienen como clase alguno de los elementos de subclasses
for clase in subclasses:
    for i in g.subjects(RDF.type, clase):
        individuals.append(i)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =prepareQuery('''
SELECT ?ind WHERE{
  ?ind rdf:type ?class.
  ?class rdfs:subClassOf* ontology:Person.
}
''',
 initNs = { "rdf": RDF, "rdfs": RDFS,"ontology":ONTOLOGY}
 )

for r in g.query(query):
  print(r.ind)

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =prepareQuery('''
SELECT ?name ?type WHERE{
  ?persona ontology:knows ontology:Rocky.
  ?persona rdf:type ?type.
  ?persona rdfs:label ?name.
}
''',
 initNs = { "rdf": RDF,"rdfs":RDFS,"ontology":ONTOLOGY}
 )

#Visualize the results
for r in g.query(query):
  print(r.name,r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =prepareQuery('''
SELECT DISTINCT ?name WHERE {
  {
    # Caso 1: persona con amigo con perro
    ?persona ontology:hasColleague ?colleague .
    ?colleague ontology:ownsPet ?pet .
  }
  UNION
  {
    # Caso 2: persona con colega, que tiene un colega con perro
    ?persona ontology:hasColleague ?colleague1 .
    ?colleague1 ontology:hasColleague ?colleague2 .
    ?colleague2 ontology:ownsPet ?pet .
  }
  ?persona rdfs:label ?name .
}
''',
 initNs = { "rdfs":RDFS,"ontology":ONTOLOGY}
 )

for r in g.query(query):
  print(r.name)

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")