# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4iDipidgFieyMjtLb4HOjaRrqNAgDFE

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
import urllib.request

url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report

g = Graph()
r = Report()

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person   = Namespace("http://oeg.fi.upm.es/resource/person/")

g.bind("ontology", ontology)
g.bind("person", person)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

for cls, label in [
    (ontology.Person,                   "Person"),
    (ontology.Professor,                "Professor"),
    (ontology.AssociateProfessor,       "AssociateProfessor"),
    (ontology.InterimAssociateProfessor,"InterimAssociateProfessor"),
    (ontology.FullProfessor,            "FullProfessor"),
]:
    g.add((cls, RDF.type, RDFS.Class))
    g.add((cls, RDFS.label, Literal(label, datatype=XSD.string)))

g.add((ontology.Professor,                 RDFS.subClassOf, ontology.Person))
g.add((ontology.AssociateProfessor,        RDFS.subClassOf, ontology.Professor))
g.add((ontology.InterimAssociateProfessor, RDFS.subClassOf, ontology.AssociateProfessor))
g.add((ontology.FullProfessor,             RDFS.subClassOf, ontology.Professor))

# Validation
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

hasColleague = ontology.hasColleague
hasName      = ontology.hasName
hasHomePage  = ontology.hasHomePage

for prop, label in [
    (hasColleague, "hasColleague"),
    (hasName, "hasName"),
    (hasHomePage, "hasHomePage"),
]:
    g.add((prop, RDF.type, RDF.Property))
    g.add((prop, RDFS.label, Literal(label, datatype=XSD.string)))

g.add((hasColleague, RDFS.domain, ontology.Person))
g.add((hasColleague, RDFS.range,  ontology.Person))

g.add((hasName, RDFS.domain, ontology.Person))
g.add((hasName, RDFS.range,  RDFS.Literal))

g.add((hasHomePage, RDFS.domain, ontology.FullProfessor))
g.add((hasHomePage, RDFS.range,  RDFS.Literal))

# Validation
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

Oscar = person.Oscar
Asun  = person.Asun
Raul  = person.Raul

g.add((Oscar, RDF.type, ontology.AssociateProfessor))
g.add((Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))

g.add((Asun, RDF.type, ontology.FullProfessor))
g.add((Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))

g.add((Raul, RDF.type, ontology.InterimAssociateProfessor))
g.add((Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

g.add((Asun, hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))
g.add((Oscar, hasName,    Literal("Oscar Corcho García", datatype=XSD.string)))
g.add((Asun, hasColleague, Raul))
g.add((Oscar, hasColleague, Asun))

# Validation
r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

from rdflib import Namespace, Literal
from rdflib.namespace import RDFS, XSD

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF  = Namespace("http://xmlns.com/foaf/0.1/")

oscar = g.value(subject=None, predicate=RDFS.label, object=Literal("Oscar", datatype=XSD.string))
if oscar is None:
    oscar = g.value(subject=None, predicate=RDFS.label, object=Literal("Oscar"))

g.add((oscar, VCARD.Given,  Literal("Oscar",  datatype=XSD.string)))
g.add((oscar, VCARD.Family, Literal("Corcho", datatype=XSD.string)))
g.add((oscar, FOAF.email,   Literal("oscar@example.org", datatype=XSD.string)))

# Validation
r.validate_task_06_04(g)
r.save_report("_Task_06")