# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoKfUyYfa2kJXqsaTBrBjFkkrfA4CztO

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

from rdflib import Graph, Namespace

# Fresh graph
g = Graph()

# Define the namespaces EXACTLY as the validator expects
person = Namespace("http://oeg.fi.upm.es/def/people#")
organization = Namespace("http://oeg.fi.upm.es/def/organization#")

# Bind them (prefix names don't matter to the validator, but are nice for serialization)
g.namespace_manager.bind('person', person, override=True)
g.namespace_manager.bind('organization', organization, override=True)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

from rdflib.namespace import RDF, RDFS, XSD
from rdflib import Literal

Person                     = person.Person
Professor                  = person.Professor
FullProfessor              = person.FullProfessor
AssociateProfessor         = person.AssociateProfessor
InterimAssociateProfessor  = person.InterimAssociateProfessor


for cls in [Person, Professor, FullProfessor, AssociateProfessor, InterimAssociateProfessor]:
    g.add((cls, RDF.type, RDFS.Class))


g.add((Professor,                 RDFS.subClassOf, Person))
g.add((FullProfessor,             RDFS.subClassOf, Professor))
g.add((AssociateProfessor,        RDFS.subClassOf, Professor))
g.add((InterimAssociateProfessor, RDFS.subClassOf, AssociateProfessor))


labels = {
    Person                   : "Person",
    Professor                : "Professor",
    FullProfessor            : "FullProfessor",
    AssociateProfessor       : "AssociateProfessor",
    InterimAssociateProfessor: "InterimAssociateProfessor",
}
for node, lab in labels.items():
    g.add((node, RDFS.label, Literal(lab, datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

from rdflib.namespace import RDF, RDFS, XSD
from rdflib import Literal

hasColleague = person.hasColleague
hasName      = person.hasName
hasHomePage  = person.hasHomePage

for prop in [hasColleague, hasName, hasHomePage]:
    g.add((prop, RDF.type, RDF.Property))


g.add((hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))
g.add((hasName,      RDFS.label, Literal("hasName",      datatype=XSD.string)))
g.add((hasHomePage,  RDFS.label, Literal("hasHomePage",  datatype=XSD.string)))


g.add((hasColleague, RDFS.domain, person.Person))
g.add((hasColleague, RDFS.range,  person.Person))

g.add((hasName, RDFS.domain, person.Person))
g.add((hasName, RDFS.range,  RDFS.Literal))

g.add((hasHomePage, RDFS.domain, person.FullProfessor))
g.add((hasHomePage, RDFS.range,  RDFS.Literal))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

from rdflib import Namespace, Literal
from rdflib.namespace import RDF, RDFS, XSD

data = Namespace("http://oeg.fi.upm.es/resource/person/")
g.namespace_manager.bind('data', data, override=True)

oscar = data.Oscar
asun  = data.Asun
raul  = data.Raul


g.add((oscar, RDF.type, person.AssociateProfessor))
g.add((asun,  RDF.type, person.FullProfessor))
g.add((raul,  RDF.type, person.AssociateProfessor))

g.add((oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))
g.add((raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))

g.add((oscar, person.hasColleague, asun))
g.add((asun,  person.hasColleague, raul))

g.add((oscar, person.hasName, Literal("Oscar Corcho Garcia", datatype=XSD.string)))

g.add((asun, person.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

from rdflib import Namespace, Literal
from rdflib.namespace import RDFS, XSD

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
foaf  = Namespace("http://xmlns.com/foaf/0.1/")

g.namespace_manager.bind('vcard', vcard, override=True)
g.namespace_manager.bind('foaf', foaf, override=True)

oscar = g.value(subject=None, predicate=RDFS.label, object=Literal("Oscar", datatype=XSD.string))

g.add((oscar, vcard.Given,  Literal("Oscar",           datatype=XSD.string)))
g.add((oscar, vcard.Family, Literal("Corcho Garcia",   datatype=XSD.string)))  # family name(s)
g.add((oscar, foaf.email,   Literal("ocorcho@fi.upm.es", datatype=XSD.string)))  # any string is fine

for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")